BxEvents/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^docs/', include('rest_framework_swagger.urls')),
    url(r'^device/', include('devices.urls', namespace='devices')),
    # url(r'^employee/', include('employees.urls', namespace='employees')),
    url(r'^event/', include('events.urls', namespace='events')),
    url(r'^notifications/', include('notifications.urls', namespace='notifications')),
    url(r'^user/', include('participants.urls', namespace='users')),
    url(r'^idea/', include('ideas.urls', namespace='ideas')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
]

events/urls.py
from .views import event_detail, event_list, event_upcoming_list, event_past_list, event_featured, event_city_list
from .views import meeting_list, register_attendance
# from .views import event_interaction, event_interaction_vote
from django.conf.urls import url
from ideas.views import idea_list, idea_vote


urlpatterns = [
    url(r'^(?P<event_id>\d+)/$', event_detail, name='event_detail'),
    url(r'^(?P<event_id>\d+)/idea/list/$', idea_list, name='idea_list'),
    url(r'^(?P<event_id>\d+)/idea/vote/$', idea_vote, name='idea_vote'),
    # url(r'^(?P<event_id>\d+)/interaction/list/$', event_interaction, name='event_interaction'),
    url(r'^city/list/$', event_city_list, name='event_city_list'),
    url(r'^featured/$', event_featured, name='event_featured'),
    # url(r'^interaction/(?P<interaction_id>\d+)/vote$', event_interaction_vote, name='event_interaction_vote'),
    url(r'^list/$', event_list, name='event_list'),
    url(r'^meeting/list/$', meeting_list, name='meeting_list'),
    url(r'^upcoming/list/$', event_upcoming_list, name='event_upcoming_list'),
    url(r'^past/list/$', event_past_list, name='event_past_list'),
    url(r'^register/attendance/$', register_attendance, name='register_attendance'),
]

ideas/urls.py
from django.conf.urls import url
from .views import idea, idea_create
from .views import idea_register_candidate, idea_register, idea_unregister, idea_unregister_candidate
from .views import idea_candidates, idea_participants, idea_candidate_approval
from .views import idea_completed, idea_open, idea_rate, idea_scores_criteria
from .views import idea_validate, idea_draft_list


urlpatterns = [
    url(r'^(?P<idea_id>\d+)/$', idea, name='idea'),
    url(r'^(?P<idea_id>\d+)/completed/$', idea_completed, name='idea_completed'),
    url(r'^(?P<idea_id>\d+)/open/$', idea_open, name='idea_open'),
    url(r'^(?P<idea_id>\d+)/register/$', idea_register, name='idea_register'),
    url(r'^(?P<idea_id>\d+)/register/candidate/$', idea_register_candidate, name='idea_register_candidate'),
    url(r'^(?P<idea_id>\d+)/unregister/$', idea_unregister, name='idea_unregister'),
    url(r'^(?P<idea_id>\d+)/unregister/candidate/$', idea_unregister_candidate, name='idea_unregister_candidate'),
    url(r'^(?P<idea_id>\d+)/validation/switch/$', idea_validate, name='idea_validate'),
    url(r'^(?P<idea_id>\d+)/candidates/$', idea_candidates, name='idea_candidates'),
    url(r'^(?P<idea_id>\d+)/candidate/approval/switch/$', idea_candidate_approval, name='idea_candidate_approval'),
    url(r'^(?P<idea_id>\d+)/participants/$', idea_participants, name='idea_participants'),
    url(r'^(?P<idea_id>\d+)/rate/$', idea_rate, name='idea_rate'),
    # url(r'^(?P<idea_id>\d+)/vote/$', idea_vote, name='idea_vote'),
    url(r'^create/$', idea_create, name='idea_create'),
    url(r'^rate/category/list/$', idea_scores_criteria, name='idea_scores_criteria'),
    url(r'^draft/event/(?P<event_id>\d+)/list/$', idea_draft_list, name='idea_draft_list'),
]

reports/urls.py
from django.conf.urls import url

from .views import index, event_information
from .views import idea_list, idea_in_development, idea_vote_results, idea_jury_results
from .views import meeting_attendance_detail, meeting_list
from .views import participants_idea


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^participants/idea/$', participants_idea, name='participants_idea'),
    url(r'^event/(?P<event_id>\d+)/$', event_information, name='event_information'),
    url(r'^event/(?P<event_id>\d+)/idea/list/$', idea_list, name='idea_list'),
    url(r'^idea/development/list/$', idea_in_development, name='ideas_in_development'),
    url(r'^idea/vote/results/$', idea_vote_results, name='ideas_vote_results'),
    url(r'^idea/jury/results/$', idea_jury_results, name='idea_jury_results'),
    url(r'^meeting/list/$', meeting_list, name='meeting_list'),
    url(r'^meeting/(?P<meeting_id>\d+)/attendance/list/$', meeting_attendance_detail, name='attendance_list'),
]

events/views.py
from constance import config
from django.shortcuts import get_object_or_404
from rest_framework import status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.exceptions import NotAcceptable
from rest_framework.pagination import PageNumberPagination
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from utils.random_item import random_element_list

from ideas.models import IdeaParticipant
from ideas.serializers import IdeaParticipantsIdeasSerializer
from participants.models import User
from participants.permissions import IsStaff
from participants.serializers import UserSerializer

from .models import Event, Interaction, City, Meeting, Attendance
from .serializers import CitySerializer, EventSerializer, InteractionSerializer, MeetingSerializer
from .serializers import AttendanceRegisterSerializer


@api_view(['GET', ])
def event_city_list(request):
    """
    Returns event city list
    """
    cities = City.objects.all()
    serializer = CitySerializer(cities, many=True)
    return Response(serializer.data, status=status.HTTP_200_OK)


@api_view(['GET', ])
def event_detail(request, event_id):
    """
    Returns event list
    """
    event = get_object_or_404(Event, pk=event_id)
    serializer = EventSerializer(event)
    return Response(serializer.data, status=status.HTTP_200_OK)


@api_view(['GET', ])
def event_featured(request):
    """
    Returns event featured
    ---
    GET:
        parameters:
            - name: city
              description: set city_id to filter events by city
              type: string
              required: false
              paramType: query
    """
    events = Event.objects.filter(is_active=True, is_featured=True)

    if request.GET.get('city'):
        city_id = int(request.GET.get('city'))
        city = get_object_or_404(City, pk=city_id)
        events_city = events.filter(city__in=[city])
        if events_city.count() > 0:
            events = events_city
        else:
            events = Event.objects.filter(is_active=True, city__in=[city])

    if events.count() > 0:
        events_upcoming = events.filter(is_upcoming=True)
        if events_upcoming.count() > 0:
            if events_upcoming.count() > 1:
                event_featured = random_element_list(events_upcoming)
            else:
                event_featured = events_upcoming[0]
        else:
            event_featured = random_element_list(events)
    else:
        events = Event.objects.filter(is_active=True)
        if events.count() > 0:
            event_featured = random_element_list(events)
        else:
            Response(status=status.HTTP_404_NOT_FOUND)

    serializer = EventSerializer(event_featured)
    return Response(serializer.data, status=status.HTTP_200_OK)


@api_view(['GET', ])
def event_interaction(request, event_id):
    """
    Returns event interactions
    ---
    GET:
        parameters:
            - name: pagination
              description: set true if you want paginated results
              type: string
              required: false
              paramType: query
    """
    event = get_object_or_404(Event, pk=event_id, is_active=True)
    interactions = Interaction.objects.filter(event=event, is_active=True)
    if request.GET.get('pagination'):
        pagination = request.GET.get('pagination')
        if pagination == 'true':
            paginator = PageNumberPagination()
            results = paginator.paginate_queryset(interactions, request)
            serializer = InteractionSerializer(results, many=True)
            return paginator.get_paginated_response(serializer.data)
        else:
            return Response(status=status.HTTP_400_BAD_REQUEST)
    else:
        serializer = InteractionSerializer(interactions, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)


@api_view(['PATCH', ])
def event_interaction_vote(request, interaction_id):
    """
    Add +1 vote to interaction votes count
    """
    interaction = get_object_or_404(Interaction, pk=interaction_id, is_active=True)
    if interaction.event.is_interaction_active:
        interaction.votes += 1
        interaction.save()
    serializer = InteractionSerializer(interaction)
    return Response(serializer.data, status=status.HTTP_202_ACCEPTED)


@api_view(['GET', ])
def event_list(request):
    """
    Returns event list
    ---
    GET:
        parameters:
            - name: city
              description: set city_id to filter events by city
              type: string
              required: false
              paramType: query
    """
    events = Event.objects.all()
    if request.GET.get('city'):
        city_id = int(request.GET.get('city'))
        city = get_object_or_404(City, pk=city_id)
        events = Event.objects.filter(city__in=[city])
    if request.GET.get('pagination'):
        pagination = request.GET.get('pagination')
        if pagination == 'true':
            paginator = PageNumberPagination()
            results = paginator.paginate_queryset(events, request)
            serializer = EventSerializer(results, many=True)
            return paginator.get_paginated_response(serializer.data)
        else:
            return Response(status=status.HTTP_400_BAD_REQUEST)
    else:
        serializer = EventSerializer(events, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)


@api_view(['GET', ])
def event_upcoming_list(request):
    """
    Returns upcoming event list
    ---
    GET:
        parameters:
            - name: city
              description: set city_id to filter events by city
              type: string
              required: false
              paramType: query
    """
    events = Event.objects.filter(is_upcoming=True, is_active=True)
    if request.GET.get('city'):
        city_id = int(request.GET.get('city'))
        city = get_object_or_404(City, pk=city_id)
        events = events.filter(city__in=[city])
    if request.GET.get('pagination'):
        pagination = request.GET.get('pagination')
        if pagination == 'true':
            paginator = PageNumberPagination()
            results = paginator.paginate_queryset(events, request)
            serializer = EventSerializer(results, many=True)
            return paginator.get_paginated_response(serializer.data)
        else:
            return Response(status=status.HTTP_400_BAD_REQUEST)
    else:
        serializer = EventSerializer(events, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)


@api_view(['GET', ])
def event_past_list(request):
    """
    Returns past event list
    ---
    GET:
        parameters:
            - name: city
              description: set city_id to filter events by city
              type: string
              required: false
              paramType: query
    """
    events = Event.objects.filter(is_upcoming=False, is_active=True)
    if request.GET.get('city'):
        city_id = int(request.GET.get('city'))
        city = get_object_or_404(City, pk=city_id)
        events = events.filter(city__in=[city])
    if request.GET.get('pagination'):
        pagination = request.GET.get('pagination')
        if pagination == 'true':
            paginator = PageNumberPagination()
            results = paginator.paginate_queryset(events, request)
            serializer = EventSerializer(results, many=True)
            return paginator.get_paginated_response(serializer.data)
        else:
            return Response(status=status.HTTP_400_BAD_REQUEST)
    else:
        serializer = EventSerializer(events, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)


@api_view(['GET', ])
@permission_classes((IsAuthenticated, IsStaff))
def meeting_list(request):
    """
    Returns meetings list to register attendance
    ---
    GET:
        response_serializer: events.serializers.MeetingSerializer
        parameters:
            - name: event
              description: set event_id to filter meetings by event
              type: string
              required: false
              paramType: query
    """
    meetings = Meeting.objects.all().filter(is_active=True)
    if request.GET.get('event'):
        event_id = int(request.GET.get('event'))
        event = get_object_or_404(Event, pk=event_id)
        meetings = meetings.filter(event=event)
    serializer = MeetingSerializer(meetings, many=True)
    return Response(serializer.data, status=status.HTTP_200_OK)


@api_view(['POST', ])
@permission_classes((IsAuthenticated, IsStaff))
def register_attendance(request):
    """
    Register attendance to a meeting
    ---
    POST:
        serializer: events.serializers.AttendanceRegisterSerializer
    """
    serializer = AttendanceRegisterSerializer(data=request.data)
    if serializer.is_valid(raise_exception=True):
        meeting = get_object_or_404(Meeting, pk=serializer.validated_data['meeting_id'])
        user = get_object_or_404(User, email=serializer.validated_data['user_email'])
        try:
            Attendance.objects.create(meeting=meeting, participant=user)
        except Exception as e:
            print(e)
            raise NotAcceptable(config.PARTICIPANT_REGISTERED)

        idea_participant = IdeaParticipant.objects.filter(user=user)
        user_serializer = UserSerializer(user)
        idea_serializer = IdeaParticipantsIdeasSerializer(idea_participant, many=True)
        return Response({'user': user_serializer.data,
                         'ideas': idea_serializer.data}, status=status.HTTP_200_OK)

reports/views.py
from django.db.models import Count
from django.shortcuts import render, get_object_or_404

from events.models import Attendance, Event, Meeting, EventParticipant
from ideas.models import Idea, IdeaParticipant, IdeaVotes, IdeaScores


def index(request):
    return render(request, 'index.html')


def event_information(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    participants_registered = EventParticipant.objects.filter(event=event)
    attendances = Attendance.objects.filter(meeting__event=event).values('meeting__name').annotate(
        total=Count('participant')).order_by('total')
    ideas_proposed = Idea.objects.filter(event=event)
    ideas_valid = Idea.objects.filter(event=event, is_valid=True)
    team_members = IdeaParticipant.objects.filter(idea__event=event)
    votes = IdeaVotes.objects.filter(event=event)
    context = {'event': event,
               'participants_registered': participants_registered,
               'attendances': attendances,
               'ideas_proposed': ideas_proposed,
               'ideas_valid': ideas_valid,
               'team_members': team_members,
               'votes': votes}
    return render(request, 'event.html', context)


def participants_idea(request):
    participants_list = IdeaParticipant.objects.all()
    context = {'participants_list': participants_list}
    return render(request, 'participants_idea.html', context)


def idea_list(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    list = Idea.objects.filter(event=event, is_valid=True)
    context = {'idea_list': list}
    return render(request, 'idea_list.html', context)


def idea_in_development(request):
    list = Idea.objects.filter(is_completed=True)
    context = {'idea_list': list}
    return render(request, 'idea_list.html', context)


def idea_vote_results(request):
    results = IdeaVotes.objects.all().values('idea__title',
                                             'idea__id').annotate(total=Count('participant')).order_by('-total')
    context = {'results': results}
    return render(request, 'idea_vote_results.html', context)


def idea_jury_results(request):
    results = IdeaScores.objects.all().order_by('idea')
    context = {'results': results}
    return render(request, 'idea_jury_results.html', context)


def meeting_list(request):
    meetings = Meeting.objects.all()
    context = {'meeting_list': meetings}
    return render(request, 'meeting_list.html', context)


def meeting_attendance_detail(request, meeting_id):
    attendance_list = Attendance.objects.filter(meeting=meeting_id)
    context = {'attendance_list': attendance_list}
    return render(request, 'attendance_list.html', context)

reports/templates/attendance_list.html
{% extends 'base.html' %}
{% block content %}
    <table border="1">
        <tr>
            <th>#</th>
            <th>Meeting Name</th>
            <th>Participant fullname</th>
            <th>Participant email</th>
            <th>Register datetime</th>
        </tr>
        {% for register in attendance_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ register.meeting.name }}</td>
            <td>{{ register.participant.full_name }}</td>
            <td>{{ register.participant.email }}</td>
            <td>{{ register.datetime }}</td>
        </tr>
    {% empty %}
        <tr><td>no content.</td></tr>
    {% endfor %}
    </table>
    <p><a href="{% url 'reports:meeting_list' %}">Back</a></p>
{% endblock content %}

reports/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Belatrix Events Reports</title>
</head>
<body>
    {% block content %}
    {% endblock content %}
</body>
</html>

reports/templates/event.html
{% extends 'base.html' %}
{% block content %}
    <table border="1">
        <tr><th colspan="2">Event</th></tr>
        <tr><th>Title</th><td>{{ event.title }}</td></tr>
        <tr><th>Datetime</th><td>{{ event.datetime }}</td></tr>
        <tr><th>Address</th><td>{{ event.address }}</td></tr>
        <tr><th>Participants Registered</th><td>{{ participants_registered | length }}</td></tr>
        <tr><th>Proposed ideas</th><td>{{ ideas_proposed | length }}</td></tr>
        <tr><th>Valid Ideas </th><td>{{ ideas_valid | length }}</td></tr>
        <tr><th>Team members</th><td>{{ team_members | length }}</td></tr>
        <tr><th>Votes</th><td>{{ votes | length }}</td></tr>
    </table>

    <table border="1">
        <tr><th colspan="3">Meetings Attendance</th></tr>
            <tr><th>#</th><th>Meeting</th><th>Assistants</th></tr>
        {% for register in attendances %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ register.meeting__name }}</td>
                <td>{{ register.total }}</td>
            </tr>
        {% empty %}
            <tr><td>no content.</td></tr>
        {% endfor %}
    </table>

    <p><a href="{% url 'reports:index' %}">Back</a></p>
{% endblock content %}

reports/templates/idea_jury_results.html
{% extends 'base.html' %}
{% block content %}
    <table border="1">
        <tr>
            <th>#</th>
            <th>Idea</th>
            <th>Jury</th>
            <th>Category</th>
            <th>Weight</th>
            <th>Value</th>
        </tr>
        {% for register in results %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ register.idea.title }}</td>
            <td>{{ register.jury.full_name }}</td>
            <td>{{ register.category }}</td>
            <td>{{ register.category.weight }}</td>
            <td>{{ register.value }}</td>
        </tr>
    {% empty %}
        <tr><td>no content.</td></tr>
    {% endfor %}
    </table>
    <p><a href="{% url 'reports:index' %}">Back</a></p>
{% endblock content %}

reports/templates/idea_list.html
{% extends 'base.html' %}
{% block content %}
    <table border="1">
        <tr>
            <th>#</th>
            <th>Title</th>
            <th>Author email</th>
            <th>Description</th>
            <th>Is Completed?</th>
            <th>Is Valid?</th>
        </tr>
        {% for register in idea_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ register.title }}</td>
            <td>{{ register.author.email }}</td>
            <td>{{ register.description }}</td>
            <td>{{ register.is_completed }}</td>
            <td>{{ register.is_valid }}</td>
        </tr>
    {% empty %}
        <tr><td>no content.</td></tr>
    {% endfor %}
    </table>
    <p><a href="{% url 'reports:index' %}">Back</a></p>
{% endblock content %}

reports/templates/idea_vote_results.html
{% extends 'base.html' %}
{% block content %}
    <table border="1">
        <tr>
            <th>#</th>
            <th>Idea Title</th>
            <th>Votes</th>
        </tr>
        {% for register in results %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ register.idea__title }}</td>
            <td>{{ register.total }}</td>
        </tr>
    {% empty %}
        <tr><td>no content.</td></tr>
    {% endfor %}
    </table>
    <p><a href="{% url 'reports:index' %}">Back</a></p>
{% endblock content %}

reports/templates/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Reports</h1>
<div>
    <h2>Events</h2>
    <p>
        <ul><li><a href="{% url 'reports:event_information' event_id=19 %}">Summary Hackatrix 2018</a></li></ul>
        <ul><li><a href="{% url 'reports:idea_list' event_id=19 %}">Hackatrix 2018 Valid Ideas</a></li></ul>
        <ul><li><a href="{% url 'reports:meeting_list' %}">Meetings attendance</a></li></ul>
    </p>
</div>
<div>
    <h2>Ideas</h2>
    <p>
        <ul><li><a href="{% url 'reports:ideas_in_development' %}">Ideas in development</a></li></ul>
        <ul><li><a href="{% url 'reports:ideas_vote_results' %}">Ideas Votes Results</a></li></ul>
        <ul><li><a href="{% url 'reports:idea_jury_results' %}">Ideas Jury Results</a></li></ul>
    </p>
</div>
<div>
    <h2>Participants</h2>
    <p>
        <ul><li><a href="{% url 'reports:participants_idea' %}">Participants by Projects</a></li></ul>
    </p>
</div>
{% endblock content %}

reports/templates/meeting_list.html
{% extends 'base.html' %}
{% block content %}
    <table border="1">
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Event</th>
            <th>Start date</th>
            <th>End date</th>
            <th>Is Over?</th>
            <th>Is Active?</th>
        </tr>
        {% for register in meeting_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td><a href="{% url 'reports:attendance_list' meeting_id=register.id %}">{{ register.name }}</a></td>
            <td>{{ register.event.title }}</td>
            <td>{{ register.start_date }}</td>
            <td>{{ register.end_date }}</td>
            <td>{{ register.is_over }}</td>
            <td>{{ register.is_active }}</td>
        </tr>
    {% empty %}
        <tr><td>no content.</td></tr>
    {% endfor %}
    </table>
    <p><a href="{% url 'reports:index' %}">Back</a></p>
{% endblock content %}

reports/templates/participants_idea.html
{% extends 'base.html' %}
{% block content %}
    <table border="1">
        <tr>
            <th>#</th>
            <th>Idea Title</th>
            <th>Participant Full Name</th>
            <th>Participant email</th>
        </tr>
        {% for register in participants_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ register.idea }}</td>
            <td>{{ register.user.full_name }}</td>
            <td>{{ register.user.email }}</td>
        </tr>
    {% empty %}
        <tr><td>no content.</td></tr>
    {% endfor %}
    </table>
    <p><a href="{% url 'reports:index' %}">Back</a></p>
{% endblock content %}